#/bin/bash
#SET PATH VARIABLE
ORADATA="/ORACLE/oradata"
USER="upadm"
PWD="oracle08"
EXP_PATH="/home/oraUAP/exp"
SYS_PWD="password"
CHARSET="KO16MSWIN949"

echo -n "Password:" 
read -s password

if [ "${password}" != "uaprofile" ]; then
        echo 
        exit;
fi

echo

echo "==== Welcome to createDB Script ===="
echo "   ORADATA PATH = $ORADATA "
echo "   USER = $USER "
echo "   PWD = $PWD "
echo "   SYS_PWD = $SYS_PWD "
echo "   DB CHARACTER SET = $CHARSET "
echo "   EXPORT DATA FILE PATH = $EXP_PATH "

FILE_LIST="SEQUENCE_DDL.SQL
INDEX_DDL.SQL
FUNCTION_DDL.SQL
PROCEDURE_DDL.SQL
SYNONYM_DDL.SQL
USER_TAB_PRIV_DCL.SQL
importTab.sh
export.dmp"

for file in $FILE_LIST
do
        if [ ! -f $file ]; then
                echo " $file Is Missing. Check The Files. "
                exit;
        fi
done

echo
echo "==================================="
echo "     START DB CREATION PROCESS     "
echo "==================================="

echo -n "ORACLE_SID:" 
read -r ORA_SID

export ORACLE_SID=${ORA_SID}
echo " ORACLE_SID= ${ORACLE_SID} "

echo -n "Type 'yes' to Create Database ($ORACLE_SID) : "
read -s confirm
echo ""

if [ "${confirm^^}" == "YES" ]; then

echo "==================================="
echo "     DATABASE CREATION START       "
echo "==================================="

dbca -silent -createDatabase -templateName General_Purpose.dbc -gdbname $ORACLE_SID -sid $ORACLE_SID -sysDBAUserName sys -sysDBAPassword password -responseFile NO_VALUE -characterSet $CHARSET -memoryPercentage 20 -emConfiguration NONE

echo "==================================="
echo "     DATABASE CREATION END         "
echo "==================================="
echo

echo "============================"
echo "     CHECK DB INFO          "
echo "============================"

sqlplus "/as sysdba" << EOF
SELECT INSTANCE_NAME, STATUS, DATABASE_STATUS FROM V\$INSTANCE;
SELECT * FROM GLOBAL_NAME;
SELECT NAME FROM V\$DATAFILE;
EXIT;
EOF

echo "========================================"
echo "     DATABASE OBJECT CREATION START     "
echo "========================================"
mkdir -p /ORACLE/oradata/${ORA_SID}

sqlplus "/as sysdba" << EOF
DECLARE
    RES NUMBER;
BEGIN
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'DATA01';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE DATA01 DATAFILE ''/ORACLE/oradata/${ORA_SID}/data01.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'DATA02';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE DATA02 DATAFILE ''/ORACLE/oradata/${ORA_SID}/data02.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'DATA03';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE DATA03 DATAFILE ''/ORACLE/oradata/${ORA_SID}/data03.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'DATA04';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE DATA04 DATAFILE ''/ORACLE/oradata/${ORA_SID}/data04.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'INDEX01';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE INDEX01 DATAFILE ''/ORACLE/oradata/${ORA_SID}/index01.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'INDEX02';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE INDEX02 DATAFILE ''/ORACLE/oradata/${ORA_SID}/index02.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'INDEX03';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE INDEX03 DATAFILE ''/ORACLE/oradata/${ORA_SID}/index03.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'INDEX04';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE INDEX04 DATAFILE ''/ORACLE/oradata/${ORA_SID}/index04.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'TS_MWADM';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE TS_MWADM DATAFILE ''/ORACLE/oradata/${ORA_SID}/ts_mwadm.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'BIG_IDX';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE BIG_IDX DATAFILE ''/ORACLE/oradata/${ORA_SID}/big_idx.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_TABLESPACES WHERE TABLESPACE_NAME = 'BIG_DATA';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLESPACE BIG_DATA DATAFILE ''/ORACLE/oradata/${ORA_SID}/big_data.dbf'' SIZE 64M AUTOEXTEND ON SEGMENT SPACE MANAGEMENT AUTO';
    END IF;
END;
/

DECLARE
    RES NUMBER;
BEGIN
    SELECT COUNT(*) INTO RES FROM DBA_USERS WHERE USERNAME = 'VAM';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER VAM IDENTIFIED BY oracle08 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_USERS WHERE USERNAME = 'MIG';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER MIG IDENTIFIED BY oracle08 DEFAULT TABLESPACE BIG_DATA QUOTA UNLIMITED ON BIG_DATA';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_USERS WHERE USERNAME = 'PMH';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER PMH IDENTIFIED BY oracle08 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_USERS WHERE USERNAME = 'UAPIS';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER UAPIS IDENTIFIED BY oracle08 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_USERS WHERE USERNAME = 'UPADM';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER UPADM IDENTIFIED BY oracle08 DEFAULT TABLESPACE DATA01 QUOTA UNLIMITED ON DATA01';
    END IF;
    SELECT COUNT(*) INTO RES FROM DBA_USERS WHERE USERNAME = 'UAPIFS';
    IF RES = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER UAPIFS IDENTIFIED BY oracle08 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
END;
/

CREATE ROLE CONNECT2;
GRANT CREATE VIEW, ALTER SESSION, CREATE SYNONYM, CREATE DATABASE LINK TO CONNECT2;

GRANT CONNECT, CONNECT2, RESOURCE TO VAM;
GRANT CONNECT, CONNECT2, RESOURCE TO MIG;
GRANT CONNECT, CONNECT2, RESOURCE TO PMH;
GRANT CONNECT, CONNECT2, RESOURCE TO UAPIS;
GRANT CONNECT, CONNECT2, RESOURCE TO UAPIFS;
GRANT CONNECT, CONNECT2, RESOURCE, DBA TO UPADM;

CONNECT $USER/$PWD

@SEQUENCE_DDL.SQL
EOF

./importTab.sh ${USER} ${PWD} ${EXP_PATH}

sqlplus $USER/$PWD << EOF
@INDEX_DDL.SQL
@FUNCTION_DDL.SQL
@PROCEDURE_DDL.SQL
@SYNONYM_DDL.SQL
@USER_TAB_PRIV_DCL.SQL

DECLARE 
JOB_NO NUMBER;
BEGIN
DBMS_JOB.SUBMIT(JOB_NO, 'ADD_PARTITIONS();', SYSDATE, 'SYSDATE + 1');
DBMS_OUTPUT.PUT_LINE('JOB NO : '||JOB_NO);
DBMS_JOB.RUN(JOB_NO);
END;
/
EOF

echo "========================================"
echo "     DATABASE OBJECT CREATION END       "
echo "========================================"

echo "==================================="
echo "     END DB CREATION PROCESS     "
echo "==================================="
else
        echo 
        exit;
fi