#/bin/bash
#SET PATH VARIABLE
EXP_PATH="/home/uapwas/user/wony"
USER="upadm"
PWD="oracle08"
SYS_PWD="password"
CHARSET="KO16MSWIN949"

echo -n "EXP_PATH:" 
read -r EXP_PATH

echo -n "USER:" 
read -r USER

echo -n "PWD:" 
read -r PWD

echo -n "ORACLE_SID:" 
read -r ORACLE_SID

echo -n "SYS_PWD:" 
read -r SYS_PWD

echo "==== Welcome to createDB Script ===="
echo "   EXP_PATH = $EXP_PATH "
echo "   USER = $USER "
echo "   PWD = $PWD "
echo "   SYS_PWD = $SYS_PWD "
echo "   DB CHARACTER SET = $CHARSET "

echo -n "Password:" 
read -s password

if [ "${password}" != "uaprofile" ]; then
	echo 
	exit;
fi

echo
LIST="TB_SERVICE_LIST, TB_IF_BUF, TB_CUST_PROF, TB_USER_GRP, TB_ADLT_AUTH_BUF, TB_CP_PROFILE, TB_SERVICE_BUF, TB_REQ_JOB, \
TB_MENU_ACCESS_AUTH, ADDED_COIS_BASE, AUDIT_GLR_BASE, BUFFER_CACHE, DEVICE_NGM, JOB_LOG, MVNO_SVC, PLAN_TABLE, STATS_20140211, \
STATS_20141113, STATS_20141114, TBASE_TEMP, TB_ACL_INFO, TB_ACL_INFO_BAK, TB_ACL_INFO_HIST, TB_ADDED_SVC, TB_ADDED_SVC_GROUP, \
TB_ADDED_SVC_REQ_BUF, TB_ADLT_AUTH_REPORT, TB_ADULT_SERVICE_LOG, TB_APPROVED_CUST, TB_APPROVED_CUST_HIST, TB_ASIS_AUTH_CODE, \
TB_ATTACH_FILE, TB_AUTH_MOD_BUF, TB_BOOKMARK, TB_BPCIM_IF, TB_BP_FILELOG, TB_BULLETIN, TB_BUNDLE, TB_BUNDLE_ATTRIBUTE, TB_BUNDLE_DEVICE, \
TB_BUNDLE_WHERE, TB_CDS_CHANGE_ADDED_CODE, TB_CDS_IFS_ERR, TB_CDS_IFS_ERR_IMSI, TB_CDS_LOG, TB_CD_SOURCE, TB_CD_TP, TB_CD_VAL, \
TB_CHARGE_CD, TB_CHG_PLUS, TB_CHG_PLUS_HIST, TB_CODE, TB_COMPO, TB_CP, TB_CP_ALARM_HIST, TB_CP_ALARM_HIST_TEMP, TB_CP_CONN_TEMPLATE, \
TB_CP_ERROR_CODE, TB_CP_ERR_INFO, TB_CP_ERR_SUM, TB_CP_HIST, TB_CP_IF_SUM, TB_CP_IP, TB_CP_IP_BUF, TB_CP_JOB_LIST, TB_CP_LDAP_CONN, \
TB_CP_LDAP_CONN_HIST, TB_CP_LDAP_CONN_MIN, TB_CP_LDAP_CONN_STAT, TB_CP_LDAP_MONITOR, TB_CP_LDAP_MONITOR_STAT, TB_CP_MNG, \
TB_CP_PROFILE_CONN, TB_CP_PROFILE_MAP, TB_CP_PROFILE_MASTER, TB_CP_PROFILE_MASTER_20170531, TB_CP_PROFILE_MASTER_20170602, \
TB_CP_RECONN_HIST, TB_CP_REQ_LOG, TB_CP_REQ_SUM, TB_CP_SERVICE_INFO, TB_CP_SVC_SUM, TB_CP_TRANSACTION, TB_CP_TRAN_DAILY, \
TB_CP_TRAN_HOUR, TB_CP_TRAN_MIN, TB_CP_TRAN_MIN10, TB_CP_USER_GRP, TB_CSCENTER_BUF, TB_CUST_ADDED_SVC, TB_CUST_ADDED_SVC_HIST, \
TB_CUST_BLACK_LIST, TB_CUST_CHILD, TB_CUST_CHILD_HIST, TB_CUST_GRANT, TB_CUST_GRANT_HIST, TB_CUST_GRANT_REQ_BUF, TB_CUST_PERSON, \
TB_CUST_PROF_GLR_HIST, TB_CUST_PROF_HIST, TB_CUST_UAP_MW_BUF, TB_CUST_UAP_MW_BUF_HIST, TB_CUST_UAP_PMH_BUF, TB_CUST_UAP_VAM_BUF, \
TB_CUS_AUTH, TB_CUS_AUTH_BUF, TB_CUS_AUTH_HIST, TB_CUS_INFO_HIST, TB_DAILY_JOB, TB_DAILY_JOB_FILE, TB_DATA_TP, TB_DATEXTRACT_BUF, \
TB_DEVICE_BOOL, TB_ECT_SUPPORT_BUF, TB_EMAIL_SEND, TB_EMAIL_SEND_CROB, TB_EMSG_TEMPLET, TB_ENTLOG, TB_EXCEPTION_BOOL, TB_FAMILY_SITE, \
TB_FAQ, TB_FLATSUM_BUF, TB_FLATSUM_CONN_BUF, TB_FMI_SRC, TB_GLR_IFS_ERR, TB_GLR_IFS_ERR_TMP, TB_GLR_RECOVERY, TB_GLR_RESET, \
TB_GLR_RESET_MINUS, TB_GLR_TEMP, TB_GLR_TEMP1, TB_GLR_TMP, TB_GRANT, TB_GRANT_MENU, TB_ICAS_ATTR, TB_ICAS_AUTH, TB_ICAS_AUTH_BUF, \
TB_ICAS_AUTH_HIST, TB_ICAS_COMPO, TB_ICAS_GRANT, TB_ICAS_GRANT_HIST, TB_ICAS_GRANT_REQ_BUF, TB_ICAS_SUB_COMPO, TB_ICAS_TEST_NUM_BUF, \
TB_IFS_REQ_SUM, TB_IF_REPORT, TB_IP_MOD_BUF, TB_IRM_MAP, TB_JOB_LINK, TB_JOB_LOG, TB_JOB_MSG_FLOW, TB_JOB_PROC_FLOW, TB_JOB_STATISTIC, \
TB_JOB_STATISTIC_BATCH, TB_LDAP_CONN_CTR_HIST, TB_LDAP_CONN_CTR_INFO, TB_LIMIT_EVEN, TB_LIMIT_HIST, TB_LIMIT_ODD, TB_LOGIN_HIST, \
TB_LOG_TRAILER_OFFSET, TB_MENU, TB_MENU_EXEC_AUTH, TB_MENU_LIST, TB_META_BUF, TB_MNG_TRANS_BUF, TB_MP_INFO_BUF, TB_MSG_QUEUE, \
TB_MSG_RESULT, TB_MULTI_NUM, TB_MULTI_NUM_HIST, TB_NATEIFS_TRAN_DAILY, TB_NATEIFS_TRAN_HOUR, TB_NATEIFS_TRAN_MIN, TB_NATEIFS_TRAN_MIN10, \
TB_NGCP_AUTH, TB_NM_SPACE, TB_NOMODEL_INFO, TB_NOTICE, TB_NOTIFICATION, TB_OPEN_CP, TB_OPEN_CP_HIST, TB_OPEN_GRANT, TB_OPEN_GRANT_BUF, \
TB_OPEN_GRANT_HIST, TB_OPEN_GRANT_REQ_BUF, TB_OPMD, TB_OPMD_HIST, TB_PARTNER, TB_PARTNER_COMPANY, TB_PARTNER_COMPANY_IF, \
TB_PARTNER_COMPANY_IF_BAK, TB_PARTNER_COMPANY_IF_HIST, TB_PDS, TB_PMH_IFS_LOG, TB_PMH_IFS_LOG_BAK_20171215, TB_PROC_BAD_LOG, \
TB_PROC_JOB_HIST, TB_PROC_RETRY, TB_PROC_TRANS_HIST, TB_PROC_USERS, TB_QNA, TB_REQ_JOB_MAPPING, TB_RET_CMT, TB_SERVER_INFO, \
TB_SERVER_INFO_BUF, TB_SERVER_INFO_HIST, TB_SERVICE, TB_SERVICE_LIST_HIST, TB_SHARE_SVC, TB_SKT_CUST_HIST_JOB, TB_SKT_EMP, \
TB_SKT_MGM_USER, TB_SMSG_TEMPLET, TB_SMS_AUTH, TB_SMS_SEND, TB_SRVC_AGENCY_LINK, TB_SRVC_TRANS_BUF, TB_SUB_COMPO, TB_SVC_UAP_MW_BUF, \
TB_SVC_UAP_VAM_BUF, TB_SYNC_CHECK, TB_SYNC_CHECK_BACK, TB_SYNC_CHECK_RESULT, TB_SYNC_CODE, TB_TESTMP_BUF, TB_TEST_NUM, TB_TEST_NUM_HIST, \
TB_TEST_NUM_ICAS_LOG, TB_TEST_NUM_REQ_BUF, TB_TMP_CUST_ADDED_SVC, TB_TMP_CUST_PERSON, TB_TMP_CUST_PROF, TB_TMP_MDN_JANG, TB_UAF_ATTR, \
TB_UAF_ATTR_VAL, TB_UAF_MAP, TB_UAF_UAP_MAPPING, TB_UAP, TB_UAPROF_AUTH, TB_UAPROF_AUTH_BUF, TB_UAPROF_AUTH_HIST, TB_UAP_ATTR, \
TB_UAP_ATTR_LIST, TB_UAP_ATTR_VAL, TB_UAP_CHANGE, TB_UAP_DEVICE_HIST_LOG, TB_UAP_DUP, TB_UAP_GRANT, TB_UAP_GRANT_HIST, \
TB_UAP_GRANT_REQ_BUF, TB_UAP_REQ_BUF, TB_UAP_SCHEMA_HIST_LOG, TB_UAP_VAM_BUF_HIST, TB_UPLOAD_FILE_LIST, TB_URI_REF, TB_USER, \
TB_USER_ADD_GROUP, TB_USER_GRANT, TB_USER_GRANT_REQ_BUF, TB_USER_LIST, TB_USER_LIST_BUF, TB_USER_LIST_IF, TB_USER_LIST_IF_HIST, \
TB_USER_PRIMARY_GROUP, TB_USER_PWD_HIST, TB_VAM_SEND_DATA, TB_VAM_SEND_DATA_20180613, TB_VAM_SEND_RETRY, TB_WAP_LOG_ERR, TB_WAP_PRIME_DUP, \
TB_WORK_CD, TB_WORK_MAPPING, TEMP_GLR_IMSI, TEMP_IMSI_GLR_ERROR, TEMP_TB_UAP_DUP, TMP_ADDED_CUST, TMP_BOOL_CUST, TMP_GLR_ERR, \
TMP_GLR_F2C1, TMP_ICAS_ATTR, TMP_IMSI_LIST, TMP_PARTNER_COMPANY, TMP_SVC_JANG_LIST, TMP_SYNC_CHECK_RESULT_FILE, TMP_SYNC_CODE, \
TMP_SYNC_CODE2, TMP_USER, TMP_USER_LIST, UA_MDN_TEMP, VAM_PKG_ADDED_SVC_BK, VAM_PKG_ADDED_SVC_GROUP_BK, XTOOL_PLAN_TABLE"

#exp upadm/oracle08 tables=$LIST file=/home/oracle/user/wony/export.dmp log=/home/oracle/user/wony/export.log query=" 'where rownum < 10000' " GRANTS=N INDEXES=N CONSTRAINTS=N TRIGGERS=N STATISTICS=NONE
exp ${USER}/${PWD}@${ORACLE_SID} tables=$LIST file=${EXP_PATH}/export.dmp log=${EXP_PATH}/export.log GRANTS=N INDEXES=N CONSTRAINTS=N TRIGGERS=N STATISTICS=NONE